document.addEventListener('DOMContentLoaded', async function(){
  if(!(await MISA.requireAdmin())) {
    console.warn('MISA: current Supabase account is not authorized as an admin.');
    return;
  }
  const form=document.getElementById('productForm'), imageInput=document.getElementById('pImage'), imageDrop=document.getElementById('imageDrop'), dropHint=document.getElementById('dropHint'), heading=document.getElementById('formHeading'), submit=document.getElementById('submitBtn'), cancel=document.getElementById('cancelEditBtn'), note=document.getElementById('formNote'), search=document.getElementById('adminSearchInput'), filter=document.getElementById('adminCategoryFilter'), body=document.getElementById('adminTableBody');
  let pendingFile=null, pendingPreview='', editingId=null, activeCategory='all';
  function normalizeLink(raw){if(!raw)return ''; if(!/^https?:\/\//i.test(raw))raw='https://'+raw; return MISA.safeUrl(raw);}
  imageInput.addEventListener('change',()=>{pendingFile=imageInput.files[0]||null;if(pendingFile){pendingPreview=URL.createObjectURL(pendingFile);showPreview(pendingPreview)}});
  imageDrop.addEventListener('dragover',e=>{e.preventDefault();imageDrop.classList.add('dragover')}); imageDrop.addEventListener('dragleave',()=>imageDrop.classList.remove('dragover')); imageDrop.addEventListener('drop',e=>{e.preventDefault();imageDrop.classList.remove('dragover');const f=e.dataTransfer.files[0];if(f&&f.type.startsWith('image/')){pendingFile=f;pendingPreview=URL.createObjectURL(f);showPreview(pendingPreview)}});
  function showPreview(src){dropHint.style.display='none';let img=imageDrop.querySelector('img');if(!img){img=document.createElement('img');imageDrop.appendChild(img)}img.src=src;}
  function clearPreview(){dropHint.style.display='';const img=imageDrop.querySelector('img');if(img)img.remove();pendingFile=null;pendingPreview='';imageInput.value='';}
  async function uploadImage(file){if(!file)return '';if(file.size>6*1024*1024)throw new Error('Image is larger than 6MB. Please choose a smaller image.');const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'');const path=`products/${crypto.randomUUID()}.${ext}`;const {error}=await MISA.sb.storage.from(MISA_CONFIG.IMAGE_BUCKET).upload(path,file,{contentType:file.type||'image/jpeg',cacheControl:'31536000',upsert:false});if(error)throw error;const {data}=MISA.sb.storage.from(MISA_CONFIG.IMAGE_BUCKET).getPublicUrl(path);return data.publicUrl;}
  form.addEventListener('submit',async e=>{e.preventDefault();submit.disabled=true;note.textContent='Saving...';try{const name=document.getElementById('pName').value.trim(),price=Number(document.getElementById('pPrice').value),category=document.getElementById('pCategory').value,description=document.getElementById('pDesc').value.trim(),link=normalizeLink(document.getElementById('pLink').value.trim());if(!name||!Number.isFinite(price)||price<0)throw new Error('Please enter a valid product name and price.');let image_url='';if(pendingFile)image_url=await uploadImage(pendingFile);else if(editingId){const old=MISA.getProducts().find(p=>p.id===editingId);image_url=old?.image||'';}const payload={name,price,category,description,link,image_url,hidden:false};let result;if(editingId)result=await MISA.sb.from('products').update(payload).eq('id',editingId);else result=await MISA.sb.from('products').insert(payload);if(result.error)throw result.error;await MISA.refreshProducts();exitEdit();render();note.textContent='Saved successfully.';}catch(err){console.error(err);note.textContent=err.message||'Unable to save product.';}finally{submit.disabled=false}});
  cancel.addEventListener('click',exitEdit); search.addEventListener('input',applyFilters);
  function exitEdit(){editingId=null;form.reset();clearPreview();document.getElementById('pCategory').value='Other';heading.textContent='Post a New Product';submit.textContent='Post Product';cancel.hidden=true;}
  function enterEdit(p){editingId=p.id;document.getElementById('pName').value=p.name;document.getElementById('pPrice').value=p.price;document.getElementById('pCategory').value=MISA.normalizeCategory(p.category);document.getElementById('pDesc').value=p.desc||'';document.getElementById('pLink').value=p.link||'';if(p.image)showPreview(p.image);heading.textContent='Edit Product';submit.textContent='Save Changes';cancel.hidden=false;form.scrollIntoView({behavior:'smooth'});}
  function render(){renderFilter();body.innerHTML=MISA.getProducts().map(p=>row(p)).join('');body.querySelectorAll('[data-action=edit]').forEach(b=>b.onclick=()=>enterEdit(MISA.getProducts().find(p=>p.id===b.dataset.id)));body.querySelectorAll('[data-action=toggle]').forEach(b=>b.onclick=async()=>{b.disabled=true;const p=MISA.getProducts().find(p=>p.id===b.dataset.id);if(!p)return;const {error}=await MISA.sb.from('products').update({hidden:!p.hidden}).eq('id',p.id);if(error)alert(error.message);await MISA.refreshProducts();render();});body.querySelectorAll('[data-action=delete]').forEach(b=>b.onclick=async()=>{const p=MISA.getProducts().find(p=>p.id===b.dataset.id);if(!p||!confirm(`Delete product "${p.name}"?`))return;const {error}=await MISA.sb.from('products').delete().eq('id',p.id);if(error){alert(error.message);return}MISA.saveSavedIds(MISA.getSavedIds().filter(id=>id!==p.id));await MISA.refreshProducts();render();});applyFilters();}
  function row(p){const c=MISA.normalizeCategory(p.category),color=MISA.CATEGORY_COLORS[c]||MISA.CATEGORY_COLORS.Other;return `<div class="admin-row" data-name="${MISA.escapeHtml(MISA.removeVietnameseTones(p.name+' '+c))}" data-category="${MISA.escapeHtml(c)}"><div class="col-img">${p.image?`<img loading="lazy" src="${MISA.escapeHtml(p.image)}" alt="${MISA.escapeHtml(p.name)}">`:'<div class="row-img-placeholder"></div>'}</div><div class="col-name" data-label="Name: ">${MISA.escapeHtml(p.name)}</div><div class="col-price" data-label="Price: ">${MISA.formatPrice(p.price)}</div><div class="col-cat" data-label="Category: "><span class="category-badge" style="background:${color}">${MISA.escapeHtml(c)}</span></div><div class="col-status" data-label="Status: "><span class="status-badge ${p.hidden?'is-hidden':'is-visible'}">${p.hidden?'Hidden':'Visible'}</span></div><div class="col-actions"><button type="button" class="row-btn edit-btn" data-action="edit" data-id="${p.id}">Edit</button><button type="button" class="row-btn toggle-btn" data-action="toggle" data-id="${p.id}">${p.hidden?'Show':'Hide'}</button><button type="button" class="row-btn delete-btn" data-action="delete" data-id="${p.id}">Delete</button></div></div>`}
  function renderFilter(){const cats=['all',...Object.keys(MISA.CATEGORY_COLORS)];filter.innerHTML=cats.map(c=>`<button type="button" class="category-chip${c===activeCategory?' active':''}" data-value="${c}">${c==='all'?'All':c}</button>`).join('');filter.querySelectorAll('.category-chip').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.value;renderFilter();applyFilters()});}
  function applyFilters(){const q=MISA.removeVietnameseTones(search.value.trim());body.querySelectorAll('.admin-row').forEach(r=>{r.style.display=(!q||r.dataset.name.includes(q))&&(activeCategory==='all'||r.dataset.category===activeCategory)?'':'none'})}
  const top=document.querySelector('.manage-header'); if(top){const logout=document.createElement('button');logout.type='button';logout.className='row-btn delete-btn';logout.textContent='Sign out';logout.onclick=async()=>{await MISA.sb.auth.signOut();location.replace('index.html')};top.appendChild(logout)}
  render();
});
